name: Triquetra
on: [push]
jobs:
  Sanity-Studio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '.sanity-studio/**/*.*'
              - '**./*.schema.js'

      - if: steps.changes.outputs.src == 'true'
        name: Deploy Sanity Studio
        steps:
          - uses: actions/checkout@v2
          - uses: amondnet/vercel-action@v20
            with:
              vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
              # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
              vercel-args: "--prod" #Optional
              vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
              vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
              working-directory: ./.sanity-studio
              alias-domains: triquetra-sanity-{{BRANCH}}.vercel.dev
